"use client";

import { useState, useCallback, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";

type ThreatType = "ESD" | "EMI" | "EMP";
const THREAT_TYPES: ThreatType[] = ["ESD", "EMI", "EMP"];

interface DefinitionChallenge {
  id: string;
  threat: ThreatType;
  fullName: string;
  definition: string;
  detailHint: string;
  aliases: string[];
}

interface ScenarioChallenge {
  id: string;
  incident: string;
  context: string;
  answer: ThreatType;
  explanation: string;
  aliases: string[];
}

interface SpecQuestion {
  id: string;
  category: "Threat Mechanics" | "Area of Effect" | "Interference Sources";
  prompt: string;
  options: string[];
  answer: string;
  explanation: string;
}

const initialDefinitions: DefinitionChallenge[] = [
  {
    id: "def-esd",
    threat: "ESD",
    fullName: "Electrostatic Discharge",
    definition: "Essentially a static electricity zap that can be destructive to sensitive electronics and components.",
    detailHint: "Occurs when accumulated electrostatic charge transfers between surfaces at different electrical potentials.",
    aliases: ["esd", "electrostatic discharge", "electro static discharge", "electrostatic"],
  },
  {
    id: "def-emi",
    threat: "EMI",
    fullName: "Electromagnetic Interference",
    definition: "Often temporary disturbances that may take out or interfere with Wi-Fi or disrupt electronics briefly.",
    detailHint: "Generated by environmental and electrical noise sources like storms, generators, and power lines.",
    aliases: ["emi", "electromagnetic interference", "electro magnetic interference", "interference"],
  },
  {
    id: "def-emp",
    threat: "EMP",
    fullName: "Electromagnetic Pulse",
    definition: "A high-intensity, very destructive burst of electromagnetic energy caused by things like lightning strikes or nuclear explosions.",
    detailHint: "Induces damaging high-voltage surges that permanently destroy solid-state electronic circuits.",
    aliases: ["emp", "electromagnetic pulse", "electro magnetic pulse", "pulse"],
  },
];

const initialScenarios: ScenarioChallenge[] = [
  {
    id: "scen-carpet-motherboard",
    incident: "A technician walks across a carpeted server room floor and touches an exposed RAM module, resulting in silent component death.",
    context: "Physical contact discharge causing hardware breakdown",
    answer: "ESD",
    explanation: "ESD occurs when static electricity accumulated on a person discharges into sensitive silicon components.",
    aliases: ["esd", "electrostatic discharge"],
  },
  {
    id: "scen-generator-wifi",
    incident: "Office Wi-Fi experiences high latency and temporary connection drops whenever a heavy backup diesel generator starts running.",
    context: "Inductive motor noise creating wireless transmission disturbances",
    answer: "EMI",
    explanation: "Heavy generators generate electromagnetic interference (EMI) that can temporarily disrupt Wi-Fi and network signals.",
    aliases: ["emi", "electromagnetic interference"],
  },
  {
    id: "scen-lightning-local",
    incident: "A direct lightning strike hits the rooftop antenna, causing a localized surge that completely fries connected network gear in the facility.",
    context: "Localized high-energy pulse with a small area of effect",
    answer: "EMP",
    explanation: "Lightning strikes generate an Electromagnetic Pulse (EMP) with a small, localized area of effect that destroys electronics.",
    aliases: ["emp", "electromagnetic pulse"],
  },
  {
    id: "scen-nuclear-detonation",
    incident: "A high-altitude nuclear blast releases a massive wave of gamma radiation, instantly disabling electronic infrastructure across an entire state and initiating a 3rd world war simultaneously.",
    context: "Catastrophic pulse with an extremely large area of effect",
    answer: "EMP",
    explanation: "Nuclear explosions create an EMP with an extremely large area of effect, incapacitating electronics over vast regions.",
    aliases: ["emp", "electromagnetic pulse"],
  },
  {
    id: "scen-powerline-storm",
    incident: "Fluctuating signal noise and packet errors occur on copper lines running parallel to high-voltage overhead power lines during a storm.",
    context: "Ambient electromagnetic disruption from electrical infrastructure",
    answer: "EMI",
    explanation: "Power lines and storm activity introduce EMI into nearby unshielded cabling and electronics.",
    aliases: ["emi", "electromagnetic interference"],
  },
  {
    id: "scen-expansion-card-shock",
    incident: "A spark jumps from a technician's fingertips to the metal bracket of a PCIe expansion card when sliding it out of the packaging.",
    context: "Static electricity discharge between body and circuit board",
    answer: "ESD",
    explanation: "Sliding materials in low humidity creates static buildup that discharges as ESD upon contact.",
    aliases: ["esd", "electrostatic discharge"],
  },
];

const initialSpecQuestions: SpecQuestion[] = [
  {
    id: "spec-esd-nature",
    category: "Threat Mechanics",
    prompt: "What is ESD and what danger does it present to computer electronics?",
    options: [
      "Electrostatic Discharge: a static electricity shock that can be destructive to electronics",
      "Elysergic acid diethylamide: a synthetic drug that can cause users to hallucinate and act irrationally around electronics",
      "Electrostatic Disruption: a temporary disruption caused by a static shock that degrade performance within an area of effect",
      "Electronic Shielded Device: an enclosure standard for industrial server racks",
    ],
    answer: "Electrostatic Discharge: a static electricity shock that can be destructive to electronics",
    explanation: "ESD stands for electrostatic discharge; it is a static electricity zap capable of destroying sensitive electronic circuits.",
  },
  {
    id: "spec-emp-small",
    category: "Area of Effect",
    prompt: "What can cause an EMP with a very SMALL area of effect?",
    options: [
      "Lightning strikes",
      "Nuclear explosions",
      "Fluorescent ceiling lights",
      "Wi-Fi routers and access points",
    ],
    answer: "Lightning strikes",
    explanation: "Lightning strikes create an EMP with a very small (localized) area of effect.",
  },
  {
    id: "spec-emp-large",
    category: "Area of Effect",
    prompt: "What can cause an EMP with an EXTREMELY LARGE area of effect?",
    options: [
      "Nuclear explosions",
      "Lightning strikes",
      "Overhead high-voltage power lines",
      "Dr. Duffee when there's loud highschoolers in the hall",
    ],
    answer: "Nuclear explosions",
    explanation: "Nuclear explosions produce an EMP with an extremely large area of effect, devastating electronics across extensive regions. Dr. Duffee's reaction to loud highschoolers, whether or not you classify it as a nuclear explosion, cannot generate an EMP.",
  },
  {
    id: "spec-emi-causes",
    category: "Interference Sources",
    prompt: "What are common causes of EMI?",
    options: [
      "Storms, generators, and power lines",
      "Help I'm stuck in an online ENT study quiz I'm not supposed to be here I miss my wife and kids please tell them I love them I don't know anything about EMI just get me out of here already I want to go home",
      "Static electricity accumulated over time",
      "Lightning bolts, nuclear explosions, and electromagnetic radiation",
    ],
    answer: "Storms, generators, and power lines",
    explanation: "EMI can be caused by environmental and industrial factors such as storms, generators, power lines, and motors.",
  },
  {
    id: "spec-emi-vs-emp",
    category: "Threat Mechanics",
    prompt: "How does EMI differ from an EMP in terms of destructiveness and duration?",
    options: [
      "EMI is often a temporary disturbance that may disrupt signals/Wi-Fi, while EMP is very destructive",
      "EMI permanently destroys hardware chips, while EMP only causes temporary Wi-Fi lag",
      "EMI is triggered exclusively by nuclear detonations, while EMP is caused by power lines",
      "There is no difference; EMI and EMP are interchangeable acronyms",
    ],
    answer: "EMI is often a temporary disturbance that may disrupt signals/Wi-Fi, while EMP is very destructive",
    explanation: "EMIs are typically temporary signal disturbances, whereas EMPs are intensely destructive physical energy pulses.",
  },
  {
    id: "spec-acronym-expansions",
    category: "Threat Mechanics",
    prompt: "What full technical terms correspond to the acronyms ESD, EMI, and EMP?",
    options: [
      "Electrostatic Discharge, Electromagnetic Interference, Electromagnetic Pulse",
      "Electronic Signal Decoder, Ethernet Media Interface, Ethernet Multicast Protocol",
      "Electrostatic Disruption, Electromagnetic Interruption, Electromagnetic Propagation",
      "Electric Static Discharge, Electromagnetic Inversion, Electromagnetic Phenomenon",
    ],
    answer: "Electrostatic Discharge, Electromagnetic Interference, Electromagnetic Pulse",
    explanation: "ESD = Electrostatic Discharge, EMI = Electromagnetic Interference, EMP = Electromagnetic Pulse.",
  },
];

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

function scrambleAllQuestions(
  definitions: DefinitionChallenge[],
  scenarios: ScenarioChallenge[],
  specs: SpecQuestion[]
) {
  return {
    definitions: shuffleArray(definitions),
    scenarios: shuffleArray(scenarios),
    specs: shuffleArray(specs).map((q) => ({
      ...q,
      options: shuffleArray(q.options),
    })),
  };
}

function EsdEmiEmpQuizContent() {
  const searchParams = useSearchParams();
  const isMastery = searchParams.get("mastery") === "true";

  const [definitions, setDefinitions] = useState<DefinitionChallenge[]>(() => shuffleArray(initialDefinitions));
  const [scenarios, setScenarios] = useState<ScenarioChallenge[]>(() => shuffleArray(initialScenarios));
  const [specs, setSpecs] = useState<SpecQuestion[]>(() =>
    shuffleArray(initialSpecQuestions).map((q) => ({
      ...q,
      options: shuffleArray(q.options),
    }))
  );

  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [showResults, setShowResults] = useState<boolean>(false);
  const [isTypingMode, setIsTypingMode] = useState<boolean>(() => isMastery);
  const [hasPassedOnce, setHasPassedOnce] = useState<boolean>(() => isMastery);
  const [, setAttemptCount] = useState<number>(1);

  const handleAnswerChange = (id: string, value: string) => {
    setAnswers((prev) => ({ ...prev, [id]: value }));
  };

  const isAnswerCorrect = useCallback(
    (id: string, correctAnswer: string, aliases?: string[]) => {
      const userValue = (answers[id] || "").trim().toLowerCase();
      if (!userValue) return false;
      const target = correctAnswer.trim().toLowerCase();
      if (userValue === target) return true;
      if (aliases && aliases.some((a) => a.toLowerCase() === userValue)) return true;
      return false;
    },
    [answers]
  );

  const definitionCorrectCount = definitions.filter((d) => isAnswerCorrect(d.id, d.threat, d.aliases)).length;
  const scenarioCorrectCount = scenarios.filter((s) => isAnswerCorrect(s.id, s.answer, s.aliases)).length;
  const specCorrectCount = specs.filter((sp) => isAnswerCorrect(sp.id, sp.answer)).length;

  const totalQuestions = definitions.length + scenarios.length + specs.length;
  const totalCorrect = definitionCorrectCount + scenarioCorrectCount + specCorrectCount;
  const allCorrect = totalCorrect === totalQuestions;

  const handleValidate = () => {
    setShowResults(true);
    if (allCorrect) {
      setHasPassedOnce(true);
    }
  };

  const handleResetAndScramble = () => {
    const nextScramble = scrambleAllQuestions(initialDefinitions, initialScenarios, initialSpecQuestions);
    setDefinitions(nextScramble.definitions);
    setScenarios(nextScramble.scenarios);
    setSpecs(nextScramble.specs);
    setAnswers({});
    setShowResults(false);
    setAttemptCount((prev) => prev + 1);

    if (allCorrect || hasPassedOnce) {
      setIsTypingMode(true);
      setHasPassedOnce(true);
    }
  };

  return (
    <div className="min-h-screen flex flex-col items-center p-4 sm:p-8">
      {/* Header */}
      <header className="w-full max-w-4xl mb-8 cyber-glass-panel p-4 sm:p-5 rounded-xl border border-slate-800 shadow-xl flex flex-wrap justify-between items-center gap-4">
        <div className="flex flex-col">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] font-mono font-bold text-emerald-400 bg-emerald-950/40 border border-emerald-900/50 px-1.5 py-0.5 rounded">
              DIAGNOSTIC_MODULE
            </span>
            <span className="text-xs text-slate-500 font-mono">//</span>
            <span className="text-xs text-slate-400 font-mono">THREAT_ANALYSIS</span>
          </div>
          <h1 className="text-xl sm:text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <span className="text-emerald-400 font-mono">ENT_ROUTER_V1</span>
            <span className="text-slate-600 font-light">|</span>
            <span className="text-slate-200">ESD, EMI, & EMP</span>
          </h1>
        </div>
        <div className="flex items-center gap-3 text-xs font-mono">
          <Link
            href="/study-guide#esd-emi--emp"
            className="px-3 py-1.5 rounded-lg border border-emerald-500/30 bg-emerald-950/30 text-emerald-400 hover:bg-emerald-500/20 hover:border-emerald-400 transition-all flex items-center gap-1.5 font-bold"
          >
            <span>[STUDY_GUIDE]</span>
          </Link>
          <Link
            href="/"
            className="px-3 py-1.5 rounded-lg border border-slate-700 bg-slate-900 text-slate-300 hover:text-white hover:border-slate-600 transition-all font-bold"
          >
            {"<"} BACK TO HUB
          </Link>
        </div>
      </header>

      <main className="w-full max-w-4xl space-y-8 font-mono">
        {/* SECTION 1: Core Threat Definitions */}
        <section className="terminal-box border-l-4 border-l-emerald-500 shadow-2xl">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 mb-6 pb-3 border-b border-slate-800/80">
            <div className="flex items-center gap-2">
              <h2 className="text-base sm:text-lg font-bold text-emerald-400 font-mono">
                [PART_01: CORE_THREAT_&_ACRONYM_IDENTIFICATION]
              </h2>
            </div>
            {showResults && (
              <div className="font-mono text-xs px-2.5 py-1 rounded bg-slate-950 border border-slate-800 text-slate-300">
                SCORE:{" "}
                <span className={definitionCorrectCount === definitions.length ? "text-emerald-400 font-bold" : "text-amber-400 font-bold"}>
                  {definitionCorrectCount}
                </span>{" "}
                / {definitions.length}
              </div>
            )}
          </div>
          <p className="text-xs sm:text-sm text-slate-400 font-mono mb-6">
            Match each definition and description to the correct electrical or electromagnetic threat.
          </p>

          <div className="space-y-4">
            {definitions.map((def, index) => {
              const userVal = answers[def.id] || "";
              const isCorrect = isAnswerCorrect(def.id, def.threat, def.aliases);

              return (
                <div
                  key={def.id}
                  className={`p-4 rounded-lg border transition-all ${
                    showResults
                      ? isCorrect
                        ? "border-emerald-500/60 bg-emerald-950/20"
                        : "border-rose-500/60 bg-rose-950/20"
                      : "border-slate-800/80 bg-slate-900/70 hover:border-slate-700"
                  }`}
                >
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div className="flex items-start gap-3 grow">
                      <span className="text-xs font-mono font-bold text-emerald-400 bg-emerald-950/40 border border-emerald-900/50 px-2 py-0.5 rounded shrink-0">
                        #{String(index + 1).padStart(2, "0")}
                      </span>
                      <div>
                        <p className="text-xs sm:text-sm text-slate-200 font-medium italic font-mono leading-relaxed">{def.definition}</p>
                        <p className="text-xs text-cyan-400/80 font-mono mt-1">{def.detailHint}</p>
                      </div>
                    </div>

                    <div className="w-full md:w-64 shrink-0">
                      {isTypingMode ? (
                        <input
                          type="text"
                          placeholder="Type threat..."
                          disabled={showResults}
                          value={userVal}
                          onChange={(e) => handleAnswerChange(def.id, e.target.value)}
                          className={`w-full bg-slate-950 border p-2 text-xs sm:text-sm rounded-lg font-mono outline-none transition-colors ${
                            showResults
                              ? isCorrect
                                ? "border-emerald-500 text-emerald-400 bg-emerald-950/30"
                                : "border-rose-500 text-rose-400 bg-rose-950/30"
                              : "border-slate-700 focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400 text-slate-200"
                          }`}
                        />
                      ) : (
                        <select
                          disabled={showResults}
                          value={userVal}
                          onChange={(e) => handleAnswerChange(def.id, e.target.value)}
                          className={`w-full bg-slate-950 border p-2 text-xs sm:text-sm rounded-lg font-mono outline-none transition-colors ${
                            showResults
                              ? isCorrect
                                ? "border-emerald-500 text-emerald-400 bg-emerald-950/30"
                                : "border-rose-500 text-rose-400 bg-rose-950/30"
                              : "border-slate-700 focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400 text-slate-200"
                          }`}
                        >
                          <option value="">-- Select Threat --</option>
                          {THREAT_TYPES.map((t) => (
                            <option key={t} value={t}>
                              {t}
                            </option>
                          ))}
                        </select>
                      )}

                      {showResults && !isCorrect && (
                        <div className="mt-1 text-xs font-mono text-rose-400">
                          Expected: <strong>{def.threat}</strong> ({def.fullName})
                        </div>
                      )}
                      {showResults && isCorrect && (
                        <div className="mt-1 text-xs font-mono text-emerald-400">
                          [OK] Correct: {def.threat} ({def.fullName})
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* SECTION 2: Environmental Scenarios & Threat Classification */}
        <section className="terminal-box border-l-4 border-l-emerald-500 shadow-2xl">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 mb-6 pb-3 border-b border-slate-800/80">
            <div className="flex items-center gap-2">
              <h2 className="text-base sm:text-lg font-bold text-emerald-400 font-mono">
                [PART_02: ENVIRONMENTAL_SCENARIO_CLASSIFICATION]
              </h2>
            </div>
            {showResults && (
              <div className="font-mono text-xs px-2.5 py-1 rounded bg-slate-950 border border-slate-800 text-slate-300">
                SCORE:{" "}
                <span className={scenarioCorrectCount === scenarios.length ? "text-emerald-400 font-bold" : "text-amber-400 font-bold"}>
                  {scenarioCorrectCount}
                </span>{" "}
                / {scenarios.length}
              </div>
            )}
          </div>
          <p className="text-xs sm:text-sm text-slate-400 font-mono mb-6">
            Classify each operational scenario or hardware incident as ESD, EMI, or EMP.
          </p>

          <div className="space-y-4">
            {scenarios.map((scen, index) => {
              const userVal = answers[scen.id] || "";
              const isCorrect = isAnswerCorrect(scen.id, scen.answer, scen.aliases);

              return (
                <div
                  key={scen.id}
                  className={`p-4 rounded-lg border transition-all ${
                    showResults
                      ? isCorrect
                        ? "border-emerald-500/60 bg-emerald-950/20"
                        : "border-rose-500/60 bg-rose-950/20"
                      : "border-slate-800/80 bg-slate-900/70 hover:border-slate-700"
                  }`}
                >
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div className="flex items-start gap-3 grow">
                      <span className="text-xs font-mono font-bold text-emerald-400 bg-emerald-950/40 border border-emerald-900/50 px-2 py-0.5 rounded shrink-0">
                        #{String(index + 1).padStart(2, "0")}
                      </span>
                      <div>
                        <p className="text-xs sm:text-sm text-slate-200 font-medium font-mono leading-relaxed">{scen.incident}</p>
                        <p className="text-xs text-cyan-400/80 font-mono mt-1">{scen.context}</p>
                      </div>
                    </div>

                    <div className="w-full md:w-64 shrink-0">
                      {isTypingMode ? (
                        <input
                          type="text"
                          placeholder="Type threat..."
                          disabled={showResults}
                          value={userVal}
                          onChange={(e) => handleAnswerChange(scen.id, e.target.value)}
                          className={`w-full bg-slate-950 border p-2 text-xs sm:text-sm rounded-lg font-mono outline-none transition-colors ${
                            showResults
                              ? isCorrect
                                ? "border-emerald-500 text-emerald-400 bg-emerald-950/30"
                                : "border-rose-500 text-rose-400 bg-rose-950/30"
                              : "border-slate-700 focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400 text-slate-200"
                          }`}
                        />
                      ) : (
                        <select
                          disabled={showResults}
                          value={userVal}
                          onChange={(e) => handleAnswerChange(scen.id, e.target.value)}
                          className={`w-full bg-slate-950 border p-2 text-xs sm:text-sm rounded-lg font-mono outline-none transition-colors ${
                            showResults
                              ? isCorrect
                                ? "border-emerald-500 text-emerald-400 bg-emerald-950/30"
                                : "border-rose-500 text-rose-400 bg-rose-950/30"
                              : "border-slate-700 focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400 text-slate-200"
                          }`}
                        >
                          <option value="">-- Select Threat --</option>
                          {THREAT_TYPES.map((t) => (
                            <option key={t} value={t}>
                              {t}
                            </option>
                          ))}
                        </select>
                      )}

                      {showResults && !isCorrect && (
                        <div className="mt-1 text-xs font-mono text-rose-400">
                          Expected: <strong>{scen.answer}</strong>
                        </div>
                      )}
                      {showResults && isCorrect && (
                        <div className="mt-1 text-xs font-mono text-emerald-400">[OK] Correct: {scen.answer}</div>
                      )}
                    </div>
                  </div>

                  {showResults && (
                    <div
                      className={`mt-3 text-xs p-2.5 rounded-lg border font-mono ${
                        isCorrect
                          ? "bg-emerald-950/40 text-emerald-300 border-emerald-800/60"
                          : "bg-rose-950/40 text-rose-300 border-rose-800/60"
                      }`}
                    >
                      <span className="font-bold">{isCorrect ? "[OK] VALIDATED: " : "[!] ERROR: "}</span>
                      <span className="font-mono">{scen.explanation}</span>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        {/* SECTION 3: Technical Mechanics & Area of Effect */}
        <section className="terminal-box border-l-4 border-l-emerald-500 shadow-2xl">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 mb-6 pb-3 border-b border-slate-800/80">
            <div className="flex items-center gap-2">
              <h2 className="text-base sm:text-lg font-bold text-emerald-400 font-mono">
                [PART_03: THREAT_MECHANICS_&_AREA_OF_EFFECT]
              </h2>
            </div>
            {showResults && (
              <div className="font-mono text-xs px-2.5 py-1 rounded bg-slate-950 border border-slate-800 text-slate-300">
                SCORE:{" "}
                <span className={specCorrectCount === specs.length ? "text-emerald-400 font-bold" : "text-amber-400 font-bold"}>
                  {specCorrectCount}
                </span>{" "}
                / {specs.length}
              </div>
            )}
          </div>
          <p className="text-xs sm:text-sm text-slate-400 font-mono mb-6">
            Answer technical questions regarding threat root causes, area of effect scales, and destructiveness.
          </p>

          <div className="space-y-4">
            {specs.map((q, index) => {
              const selected = answers[q.id];
              const isCorrect = selected === q.answer;

              return (
                <div
                  key={q.id}
                  className={`p-4 rounded-lg border transition-all ${
                    showResults
                      ? isCorrect
                        ? "border-emerald-500/60 bg-emerald-950/20"
                        : "border-rose-500/60 bg-rose-950/20"
                      : "border-slate-800/80 bg-slate-900/70 hover:border-slate-700"
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <span className="text-xs font-mono font-bold text-emerald-400 bg-emerald-950/40 border border-emerald-900/50 px-2 py-0.5 rounded shrink-0">
                      #{String(index + 1).padStart(2, "0")}
                    </span>
                    <div className="grow">
                      <div className="flex items-center gap-2 mb-1.5">
                        <span className="text-[11px] px-2 py-0.5 rounded bg-slate-950 text-slate-400 border border-slate-800 font-mono">
                          {q.category}
                        </span>
                      </div>
                      <p className="text-xs sm:text-sm text-slate-200 font-medium mb-3 font-mono">{q.prompt}</p>

                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-2">
                        {q.options.map((opt) => {
                          const isOptionSelected = selected === opt;
                          const isOptionCorrect = opt === q.answer;

                          let btnStyle = "bg-slate-950 border-slate-800 text-slate-300 hover:border-emerald-500/50 hover:text-white";
                          if (showResults) {
                            if (isOptionCorrect) {
                              btnStyle = "bg-emerald-950/60 border-emerald-500 text-emerald-300 font-bold";
                            } else if (isOptionSelected && !isOptionCorrect) {
                              btnStyle = "bg-rose-950/60 border-rose-500 text-rose-300 line-through";
                            } else {
                              btnStyle = "bg-slate-950/40 border-slate-800/40 text-slate-600 opacity-60";
                            }
                          } else if (isOptionSelected) {
                            btnStyle = "bg-emerald-950/40 border-emerald-400 text-emerald-300 font-bold shadow-sm";
                          }

                          return (
                            <button
                              key={opt}
                              type="button"
                              disabled={showResults}
                              onClick={() => handleAnswerChange(q.id, opt)}
                              className={`text-left p-2.5 rounded-lg text-xs font-mono border transition-all flex items-center justify-between cursor-pointer disabled:cursor-default ${btnStyle}`}
                            >
                              <span>{opt}</span>
                              {showResults && isOptionCorrect && <span className="text-emerald-400 text-xs font-bold">[OK]</span>}
                            </button>
                          );
                        })}
                      </div>

                      {showResults && (
                        <div
                          className={`mt-3 text-xs p-2.5 rounded-lg border font-mono ${
                            isCorrect
                              ? "bg-emerald-950/40 text-emerald-300 border-emerald-800/60"
                              : "bg-rose-950/40 text-rose-300 border-rose-800/60"
                          }`}
                        >
                          <span className="font-bold">{isCorrect ? "[OK] VALIDATED: " : "[!] ERROR: "}</span>
                          <span className="font-mono">{q.explanation}</span>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* Validation / Results Actions */}
        <section className="terminal-box border-l-4 border-l-emerald-500 shadow-2xl text-center">
          {!showResults ? (
            <div className="flex flex-col items-center gap-3">
              <button
                type="button"
                onClick={handleValidate}
                className="px-8 py-3 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold font-mono text-sm rounded-lg shadow-lg shadow-emerald-950/50 hover:shadow-emerald-500/20 transition-all cursor-pointer"
              >
                VALIDATE THREAT DIAGNOSTICS
              </button>
              <p className="text-xs text-slate-400 font-mono">
                {Object.keys(answers).length} of {totalQuestions} questions answered
              </p>
            </div>
          ) : (
            <div className="space-y-6">
              <div
                className={`p-6 rounded-lg border shadow-lg ${
                  allCorrect
                    ? "bg-emerald-950/40 text-emerald-300 border-emerald-500/60 shadow-emerald-950/40"
                    : "bg-rose-950/40 text-rose-300 border-rose-500/60 shadow-rose-950/40"
                }`}
              >
                {allCorrect ? (
                  <div className="flex flex-col items-center">
                    <span className="text-lg sm:text-xl font-bold font-mono text-emerald-400 flex items-center gap-2">
                      <span>[OK]</span> SUCCESS: ALL THREAT DIAGNOSTICS SYNCHRONIZED
                    </span>
                    <p className="text-xs sm:text-sm text-emerald-300/90 font-mono mt-1">
                      Perfect Score: {totalCorrect} / {totalQuestions} correct across definitions, scenarios, and threat mechanics.
                    </p>
                  </div>
                ) : (
                  <div className="flex flex-col items-center">
                    <span className="text-lg sm:text-xl font-bold font-mono text-rose-400 flex items-center gap-2">
                      <span>[!]</span> THREAT DIAGNOSTIC MISMATCH DETECTED
                    </span>
                    <p className="text-xs sm:text-sm text-rose-300/90 font-mono mt-1">
                      Score: {totalCorrect} / {totalQuestions} correct ({totalQuestions - totalCorrect} mismatches to resolve).
                    </p>
                  </div>
                )}
              </div>

              <div className="flex justify-center">
                <button
                  type="button"
                  onClick={handleResetAndScramble}
                  className="px-6 py-2.5 border border-emerald-500/40 hover:border-emerald-400 bg-slate-900/80 hover:bg-slate-800 text-emerald-400 font-bold font-mono text-sm rounded-lg transition-all cursor-pointer"
                >
                  {allCorrect ? "RESET & SCRAMBLE" : "TRY AGAIN"}
                </button>
              </div>
            </div>
          )}
        </section>
      </main>
    </div>
  );
}

export default function EsdEmiEmpQuiz() {
  return (
    <Suspense fallback={null}>
      <EsdEmiEmpQuizContent />
    </Suspense>
  );
}
