"use client";

import { Suspense } from "react";
import { useSearchParams } from "next/navigation";
import MultiSectionQuiz, { MultiSectionConfig } from "@/components/study-quiz/MultiSectionQuiz";
import { DefinitionItem } from "@/components/study-quiz/MatchToDefinitionsQuiz";
import { QuestionQuizItem } from "@/components/study-quiz/QuestionQuiz";

const THREAT_OPTIONS = ["ESD", "EMI", "EMP"];

const initialDefinitions: DefinitionItem[] = [
  {
    id: "def-esd",
    term: "ESD",
    definition: "Essentially a static electricity zap that can be destructive to sensitive electronics and components.",
    detailHint: "Occurs when accumulated electrostatic charge transfers between surfaces at different electrical potentials.",
    aliases: ["esd", "electrostatic discharge", "electro static discharge", "electrostatic"],
  },
  {
    id: "def-emi",
    term: "EMI",
    definition: "Often temporary disturbances that may take out or interfere with Wi-Fi or disrupt electronics briefly.",
    detailHint: "Generated by environmental and electrical noise sources like storms, generators, and power lines.",
    aliases: ["emi", "electromagnetic interference", "electro magnetic interference", "interference"],
  },
  {
    id: "def-emp",
    term: "EMP",
    definition: "A high-intensity, very destructive burst of electromagnetic energy caused by things like lightning strikes or nuclear explosions.",
    detailHint: "Induces damaging high-voltage surges that permanently destroy solid-state electronic circuits.",
    aliases: ["emp", "electromagnetic pulse", "electro magnetic pulse", "pulse"],
  },
];

const initialScenarios: QuestionQuizItem[] = [
  {
    id: "scen-carpet-motherboard",
    category: "Physical Contact Discharge",
    prompt: "A technician walks across a carpeted server room floor and touches an exposed RAM module, resulting in silent component death.",
    options: THREAT_OPTIONS,
    answer: "ESD",
    explanation: "ESD occurs when static electricity accumulated on a person discharges into sensitive silicon components.",
    canTypeInHardMode: true,
    aliases: ["esd", "electrostatic discharge", "electrostatic", "static shock", "static", "static electricity"],
    keywords: ["esd"],
  },
  {
    id: "scen-generator-wifi",
    category: "Inductive Motor Noise",
    prompt: "Office Wi-Fi experiences high latency and temporary connection drops whenever a heavy backup diesel generator starts running.",
    options: THREAT_OPTIONS,
    answer: "EMI",
    explanation: "Heavy generators generate electromagnetic interference (EMI) that can temporarily disrupt Wi-Fi and network signals.",
    canTypeInHardMode: true,
    aliases: ["emi", "electromagnetic interference", "interference", "noise"],
    keywords: ["emi"],
  },
  {
    id: "scen-lightning-local",
    category: "Localized High-Energy Pulse",
    prompt: "A direct lightning strike hits the rooftop antenna, causing a localized surge that completely fries connected network gear in the facility.",
    options: THREAT_OPTIONS,
    answer: "EMP",
    explanation: "Lightning strikes generate an Electromagnetic Pulse (EMP) with a small, localized area of effect that destroys electronics.",
    canTypeInHardMode: true,
    aliases: ["emp", "electromagnetic pulse", "pulse"],
    keywords: ["emp"],
  },
  {
    id: "scen-nuclear-detonation",
    category: "Catastrophic Broad Pulse",
    prompt: "A high-altitude nuclear blast releases a massive wave of gamma radiation, instantly disabling electronic infrastructure across an entire state and initiating a 3rd world war simultaneously.",
    options: THREAT_OPTIONS,
    answer: "EMP",
    explanation: "Nuclear explosions create an EMP with an extremely large area of effect, incapacitating electronics over vast regions.",
    canTypeInHardMode: true,
    aliases: ["emp", "electromagnetic pulse", "pulse"],
    keywords: ["emp"],
  },
  {
    id: "scen-powerline-storm",
    category: "Ambient EM Disruption",
    prompt: "Fluctuating signal noise and packet errors occur on copper lines running parallel to high-voltage overhead power lines during a storm.",
    options: THREAT_OPTIONS,
    answer: "EMI",
    explanation: "Power lines and storm activity introduce EMI into nearby unshielded cabling and electronics.",
    canTypeInHardMode: true,
    aliases: ["emi", "electromagnetic interference", "interference", "noise"],
    keywords: ["emi"],
  },
  {
    id: "scen-expansion-card-shock",
    category: "Electrostatic Discharge",
    prompt: "A spark jumps from a technician's fingertips to the metal bracket of a PCIe expansion card when sliding it out of the packaging.",
    options: THREAT_OPTIONS,
    answer: "ESD",
    explanation: "Sliding materials in low humidity creates static buildup that discharges as ESD upon contact.",
    canTypeInHardMode: true,
    aliases: ["esd", "electrostatic discharge", "electrostatic", "static shock", "static", "static electricity"],
    keywords: ["esd"],
  },
];

const initialSpecQuestions: QuestionQuizItem[] = [
  {
    id: "spec-esd-nature",
    category: "Threat Mechanics",
    prompt: "What is ESD and what danger does it present to computer electronics?",
    options: [
      "Electrostatic Discharge: a static electricity shock that can be destructive to electronics",
      "Elysergic acid diethylamide: a synthetic drug that can cause users to hallucinate and act irrationally around electronics",
      "Electrostatic Disruption: a temporary disruption caused by a static shock that degrade performance within an area of effect",
      "Electronic Shielded Device: an enclosure standard for industrial server racks",
    ],
    answer: "Electrostatic Discharge: a static electricity shock that can be destructive to electronics",
    explanation: "ESD stands for electrostatic discharge; it is a static electricity zap capable of destroying sensitive electronic circuits.",
    canTypeInHardMode: false,
  },
  {
    id: "spec-emp-small",
    category: "Area of Effect",
    prompt: "What can cause an EMP with a very SMALL area of effect?",
    options: [
      "Lightning strikes",
      "Nuclear explosions",
      "Fluorescent ceiling lights",
      "Wi-Fi routers and access points",
    ],
    answer: "Lightning strikes",
    explanation: "Lightning strikes create an EMP with a very small (localized) area of effect.",
    canTypeInHardMode: true,
    aliases: [
      "lightning",
      "lightning strike",
      "lightning strikes",
      "strike",
      "strikes",
      "lightning bolt",
      "lightning bolts",
    ],
    keywords: ["lightning"],
  },
  {
    id: "spec-emp-large",
    category: "Area of Effect",
    prompt: "What can cause an EMP with an EXTREMELY LARGE area of effect?",
    options: [
      "Nuclear explosions",
      "Lightning strikes",
      "Overhead high-voltage power lines",
      "Dr. Duffee when there's loud highschoolers in the hall",
    ],
    answer: "Nuclear explosions",
    explanation: "Nuclear explosions produce an EMP with an extremely large area of effect, devastating electronics across extensive regions. Dr. Duffee's reaction to loud highschoolers, whether or not you classify it as a nuclear explosion, cannot generate an EMP.",
    canTypeInHardMode: true,
    aliases: [
      "nuclear",
      "nuclear explosion",
      "nuclear explosions",
      "nuke",
      "nuclear bomb",
      "nuclear blast",
      "nuclear detonations",
      "nuclear detonation",
    ],
    keywords: ["nuclear"],
  },
  {
    id: "spec-emi-causes",
    category: "Interference Sources",
    prompt: "What are common causes of EMI?",
    options: [
      "Storms, generators, and power lines",
      "Help I'm stuck in an online ENT study quiz I'm not supposed to be here I miss my wife and kids please tell them I love them I don't know anything about EMI just get me out of here already I want to go home",
      "Static electricity accumulated over time",
      "Lightning bolts, nuclear explosions, and electromagnetic radiation",
    ],
    answer: "Storms, generators, and power lines",
    explanation: "EMI can be caused by environmental and industrial factors such as storms, generators, power lines, and motors.",
    canTypeInHardMode: false,
  },
  {
    id: "spec-emi-vs-emp",
    category: "Threat Mechanics",
    prompt: "How does EMI differ from an EMP in terms of destructiveness and duration?",
    options: [
      "EMI is often a temporary disturbance that may disrupt signals/Wi-Fi, while EMP is very destructive",
      "EMI permanently destroys hardware chips, while EMP only causes temporary Wi-Fi lag",
      "EMI is triggered exclusively by nuclear detonations, while EMP is caused by power lines",
      "There is no difference; EMI and EMP are interchangeable acronyms",
    ],
    answer: "EMI is often a temporary disturbance that may disrupt signals/Wi-Fi, while EMP is very destructive",
    explanation: "EMIs are typically temporary signal disturbances, whereas EMPs are intensely destructive physical energy pulses.",
    canTypeInHardMode: false,
  },
  {
    id: "spec-acronym-expansions",
    category: "Threat Mechanics",
    prompt: "What full technical terms correspond to the acronyms ESD, EMI, and EMP?",
    options: [
      "Electrostatic Discharge, Electromagnetic Interference, Electromagnetic Pulse",
      "Electronic Signal Decoder, Ethernet Media Interface, Ethernet Multicast Protocol",
      "Electrostatic Disruption, Electromagnetic Interruption, Electromagnetic Propagation",
      "Electric Static Discharge, Electromagnetic Inversion, Electromagnetic Phenomenon",
    ],
    answer: "Electrostatic Discharge, Electromagnetic Interference, Electromagnetic Pulse",
    explanation: "ESD = Electrostatic Discharge, EMI = Electromagnetic Interference, EMP = Electromagnetic Pulse.",
    canTypeInHardMode: true,
    aliases: [
      "electrostatic discharge electromagnetic interference electromagnetic pulse",
      "electrostatic discharge, electromagnetic interference, electromagnetic pulse",
      "esd, emi, emp",
      "esd emi emp",
    ],
    keywords: ["electrostatic", "interference", "pulse"],
  },
];

const sections: MultiSectionConfig[] = [
  {
    id: "sec-threat-definitions",
    title: "CORE_THREAT_IDENTIFICATION",
    subtitle: "[PART_01: CORE_THREAT_&_ACRONYM_IDENTIFICATION]",
    description: "Match each definition and description to the correct electrical or electromagnetic threat.",
    type: "matching",
    matchingItems: initialDefinitions,
    matchingOptions: THREAT_OPTIONS,
  },
  {
    id: "sec-scenarios",
    title: "REAL_WORLD_INCIDENT_SCENARIOS",
    subtitle: "[PART_02: REAL_WORLD_INCIDENT_SCENARIOS]",
    description: "Analyze the field incidents and categorize whether each problem was caused by ESD, EMI, or EMP.",
    type: "questions",
    questions: initialScenarios,
  },
  {
    id: "sec-mechanics",
    title: "MECHANICS_&_ENGINEERING_SPECS",
    subtitle: "[PART_03: MECHANICS_&_ENGINEERING_SPECS]",
    description: "Validate your knowledge of causes, areas of effect, and destructive characteristics.",
    type: "questions",
    questions: initialSpecQuestions,
  },
];

function EsdEmiEmpQuizContent() {
  const searchParams = useSearchParams();
  const isMastery = searchParams.get("mastery") === "true";

  return (
    <MultiSectionQuiz
      moduleTag="DIAGNOSTIC_MODULE"
      moduleCode="THREAT_ANALYSIS"
      title="ESD, EMI, & EMP"
      studyGuideHref="/study-guide#esd-emi--emp"
      sections={sections}
      initialHardMode={isMastery}
    />
  );
}

export default function EsdEmiEmpQuiz() {
  return (
    <Suspense fallback={null}>
      <EsdEmiEmpQuizContent />
    </Suspense>
  );
}
