import { MasterActivity } from "./types";
import { MASTER_QUESTIONS } from "./questions";

export { MASTER_QUESTIONS };

export const MASTER_ACTIVITIES: MasterActivity[] = [
  {
    id: "act-wire-568b",
    moduleId: "eia-tia-standard",
    moduleName: "EIA/TIA 568B Standard",
    type: "wire-ordering",
    title: "EIA/TIA 568B Wire Sequence Interactive Pinout",
    description: "Arrange the 8 colored conductor wires into the exact EIA/TIA 568B standard pin sequence from Pin 1 to Pin 8.",
  },
  {
    id: "act-table-8023",
    moduleId: "802.3-ethernet-standards",
    moduleName: "Wired Ethernet Standards",
    type: "table",
    title: "IEEE 802.3 Wired Ethernet Standards Matrix",
    description: "Fill in the blank cells in the IEEE 802.3 Ethernet matrix covering standard names, distances, speeds, cabling, and connectors.",
    columns: [
      { key: "ieeeStandard", label: "IEEE Standard", options: ["802.3", "802.3i", "802.3u", "802.3z", "802.3an"] },
      { key: "tStandard", label: "T-Standard", options: ["10base2", "10base5", "10baseT", "100baseT", "1000baseT", "10GbaseT"] },
      { key: "maxDistance", label: "Max Distance", options: ["55m", "100m", "200m", "500m"] },
      { key: "speed", label: "Speed", options: ["10 Mb/s", "100 Mb/s", "1 Gb/s", "10 Gb/s"] },
      { key: "cableType", label: "Cable Type", options: ["Thicknet (thick coax)", "Thinnet (thin coax)", "Twisted pair"] },
      { key: "minCategory", label: "Min. Category", options: ["Cat3 or better", "Cat5 or better", "Cat5e or better"] },
      { key: "connectors", label: "Connectors", options: ["RJ45", "RJ45/RJ11", "T-connectors, BNC connectors, terminators", "Vampire Taps"] },
    ],
    rows: [
      { id: 1, ieeeStandard: "802.3", tStandard: "10base2", maxDistance: "200m", speed: "10 Mb/s", cableType: "Thinnet (thin coax)", minCategory: "-", connectors: "T-connectors, BNC connectors, terminators" },
      { id: 2, ieeeStandard: "802.3", tStandard: "10base5", maxDistance: "500m", speed: "10 Mb/s", cableType: "Thicknet (thick coax)", minCategory: "-", connectors: "Vampire Taps" },
      { id: 3, ieeeStandard: "802.3i", tStandard: "10baseT", maxDistance: "100m", speed: "10 Mb/s", cableType: "Twisted pair", minCategory: "Cat3 or better", connectors: "RJ45/RJ11" },
      { id: 4, ieeeStandard: "802.3u", tStandard: "100baseT", maxDistance: "100m", speed: "100 Mb/s", cableType: "Twisted pair", minCategory: "Cat5 or better", connectors: "RJ45" },
      { id: 5, ieeeStandard: "802.3z", tStandard: "1000baseT", maxDistance: "100m", speed: "1 Gb/s", cableType: "Twisted pair", minCategory: "Cat5e or better", connectors: "RJ45" },
      { id: 6, ieeeStandard: "802.3an", tStandard: "10GbaseT", maxDistance: "100m", speed: "10 Gb/s", cableType: "Twisted pair", minCategory: "Cat5e or better", connectors: "RJ45" },
    ],
  },
  {
    id: "act-table-80211",
    moduleId: "802.11-wireless-standards",
    moduleName: "Wireless Wi-Fi Standards",
    type: "table",
    title: "IEEE 802.11 Wireless Wi-Fi Standards Matrix",
    description: "Fill in the blank cells in the IEEE 802.11 Wi-Fi matrix covering generation names, IEEE codes, radio frequencies, maximum speeds, and nominal distances.",
    columns: [
      { key: "version", label: "Version", options: ["Wi-Fi", "Wi-Fi 1", "Wi-Fi 2", "Wi-Fi 3", "Wi-Fi 4", "Wi-Fi 5", "Wi-Fi 6"] },
      { key: "ieeeStandard", label: "IEEE Standard", options: ["802.11", "802.11b", "802.11a", "802.11g", "802.11n", "802.11ac", "802.11ax"] },
      { key: "frequency", label: "Frequency", options: ["2.4 GHz", "5 GHz", "2.4 GHz + 5 GHz"] },
      { key: "speed", label: "Speed", options: ["2 Mb/s", "11 Mb/s", "54 Mb/s", "600 Mb/s", "1 Gb/s", "14 Gb/s"] },
      { key: "distance", label: "Distance", options: ["90 ft", "100 ft", "125 ft", "225 ft"] },
    ],
    rows: [
      { id: 1, version: "Wi-Fi", ieeeStandard: "802.11", frequency: "2.4 GHz", speed: "2 Mb/s", distance: "100 ft" },
      { id: 2, version: "Wi-Fi 1", ieeeStandard: "802.11b", frequency: "2.4 GHz", speed: "11 Mb/s", distance: "100 ft" },
      { id: 3, version: "Wi-Fi 2", ieeeStandard: "802.11a", frequency: "5 GHz", speed: "54 Mb/s", distance: "100 ft" },
      { id: 4, version: "Wi-Fi 3", ieeeStandard: "802.11g", frequency: "2.4 GHz", speed: "54 Mb/s", distance: "125 ft" },
      { id: 5, version: "Wi-Fi 4", ieeeStandard: "802.11n", frequency: "2.4 GHz + 5 GHz", speed: "600 Mb/s", distance: "225 ft" },
      { id: 6, version: "Wi-Fi 5", ieeeStandard: "802.11ac", frequency: "5 GHz", speed: "1 Gb/s", distance: "90 ft" },
      { id: 7, version: "Wi-Fi 6", ieeeStandard: "802.11ax", frequency: "2.4 GHz + 5 GHz", speed: "14 Gb/s", distance: "100 ft" },
    ],
  },
  {
    id: "act-table-ip-classes",
    moduleId: "ip-address-classes",
    moduleName: "General IP Address Classes",
    type: "table",
    title: "IPv4 Address Class Allocations Matrix",
    description: "Fill in the blank cells for the standard IPv4 Class A through E network ranges, structural Net/Host divisions, default subnet masks, and network/host capacities.",
    columns: [
      { key: "ipClass", label: "Class", options: ["A", "B", "C", "D", "E"] },
      { key: "networkNumber", label: "Network Number", options: ["1-126 (or 127)", "128-191", "192-223", "224-239", "240-254"] },
      { key: "netHost", label: "Net/Host", options: ["N.H.H.H", "N.N.H.H", "N.N.N.H"] },
      { key: "subnetMask", label: "Subnet Mask", options: ["255.0.0.0", "255.255.0.0", "255.255.255.0"] },
      { key: "possibleNetworks", label: "Possible Networks", options: ["126", "16k", "2M"] },
      { key: "possibleHosts", label: "Possible Hosts", options: ["16M", "65k", "254"] },
    ],
    rows: [
      { id: 1, ipClass: "A", networkNumber: "1-126 (or 127)", netHost: "N.H.H.H", subnetMask: "255.0.0.0", possibleNetworks: "126", possibleHosts: "16M" },
      { id: 2, ipClass: "B", networkNumber: "128-191", netHost: "N.N.H.H", subnetMask: "255.255.0.0", possibleNetworks: "16k", possibleHosts: "65k" },
      { id: 3, ipClass: "C", networkNumber: "192-223", netHost: "N.N.N.H", subnetMask: "255.255.255.0", possibleNetworks: "2M", possibleHosts: "254" },
      { id: 4, ipClass: "D", networkNumber: "224-239", netHost: "-", subnetMask: "-", possibleNetworks: "-", possibleHosts: "-" },
      { id: 5, ipClass: "E", networkNumber: "240-254", netHost: "-", subnetMask: "-", possibleNetworks: "-", possibleHosts: "-" },
    ],
  },
  {
    id: "act-table-private-ip",
    moduleId: "private-ip-classes",
    moduleName: "Private IP Address Classes",
    type: "table",
    title: "RFC 1918 Private IPv4 Address Space Matrix",
    description: "Fill in the blank cells for the private Class A, B, and C IPv4 address spaces and their default subnet masks.",
    columns: [
      { key: "ipClass", label: "Class", options: ["A", "B", "C"] },
      { key: "ipRange", label: "IP Address Range", options: ["10.0.0.0 - 10.255.255.255", "172.16.0.0 - 172.31.255.255", "192.168.0.0 - 192.168.255.255"] },
      { key: "subnetMask", label: "Default Subnet Mask", options: ["255.0.0.0", "255.255.0.0", "255.255.255.0"] },
    ],
    rows: [
      { id: 1, ipClass: "A", ipRange: "10.0.0.0 - 10.255.255.255", subnetMask: "255.0.0.0" },
      { id: 2, ipClass: "B", ipRange: "172.16.0.0 - 172.31.255.255", subnetMask: "255.255.0.0" },
      { id: 3, ipClass: "C", ipRange: "192.168.0.0 - 192.168.255.255", subnetMask: "255.255.255.0" },
    ],
  },
  {
    id: "act-table-wan",
    moduleId: "wan-technologies",
    moduleName: "WAN Technologies",
    type: "table",
    title: "WAN Digital Carrier Lines Specification Table",
    description: "Complete the blank cells detailing standard throughput capacities and channel counts for North American (T-carrier) and European (E-carrier) digital lines.",
    columns: [
      { key: "carrier", label: "Carrier Standard", options: ["T1", "E1", "T3", "E3", "ISDN"] },
      { key: "channels", label: "64 Kbps Channels", options: ["24", "32", "672 (T1x28)", "512 (E1x16)", "2"] },
      { key: "speed", label: "Maximum Throughput", options: ["1.544 Mbps", "2.048 Mbps", "44.736 Mbps", "34.368 Mbps", "128 Kbps"] },
    ],
    rows: [
      { id: 1, carrier: "T1", channels: "24", speed: "1.544 Mbps" },
      { id: 2, carrier: "E1", channels: "32", speed: "2.048 Mbps" },
      { id: 3, carrier: "T3", channels: "672 (T1x28)", speed: "44.736 Mbps" },
      { id: 4, carrier: "E3", channels: "512 (E1x16)", speed: "34.368 Mbps" },
      { id: 5, carrier: "ISDN", channels: "2", speed: "128 Kbps" },
    ],
  },
];
